services:
  dns:
    build:
      context: C:\Users\20211014050023\final_project\provedor\dns\
      dockerfile: Dockerfile
    container_name: dns_container
    ports:
      - "53:53/udp"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy_container
    ports:
      - "80:80/tcp"
    depends_on:
      - web_1
      - web_2
    networks:
      - asa_network

  web_1:
    build:
      context: ./web_1
      dockerfile: Dockerfile
    container_name: web1_container
    networks:
      - asa_network

  web_2:
    build:
      context: ./web_2
      dockerfile: Dockerfile
    container_name: web2_container
    networks:
      - asa_network

networks:
  asa_network:
    driver: bridge
