servce:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy_container
    ports:
      - '80:80/tcp'
    depends_on:
      - web_1
      - web_2
    networks:
      - asa_networks

  web_1:
    build:
      context: ./web_1
      dockerfile: Dockerfile
    container_name: web1_container
    networks:
      - asa_networks

  web_2:
    build:
      context: ./web_2
      dockerfile: Dockerfile
    container_name: web2_container
    networks:
      - asa_networks

networks:
  asa-network:
    driver: bridge