services:
services:    
  db-welcome:
    image: mariadb:latest
    container_name: db-welcome
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks:
      - beach-network
    volumes:
      - db_data:/var/lib/mysql
#Containers de wordpress, um e dois. (usados para balancear carga primariamente)
  wordpress-miami:
    image: wordpress:latest
    container_name: wordpress-welcome
    depends_on:
      - db-welcome
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db-welcome
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - beach-network
      - proxy-praia
    volumes:
      - wordpress_data:/var/www/html
      - ./containers/WORDPRESS/wp-config.php:/var/www/html/wp-config.php
  wordpress-2-miami:
    image: wordpress:latest
    container_name: wordpress-2-welcome
    depends_on:
      - db-welcome
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db-welcome
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - beach-network
      - proxy-praia
    volumes:
      - wordpress_data:/var/www/html
      - ./containers/WORDPRESS/wp-config.php:/var/www/html/wp-config.php

  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    image: ssh
    container_name: ssh-welcome
    ports:
      - "2223:22"
    networks:
      - beach-network

  proxy-welcome:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy-welcome
    depends_on:
      - wordpress-welcome
      - wordpress-2-welcome
    networks:
      - beach-network
      - proxy-life
    dns:
      - 192.168.0.3 # Adiciona o servidor DNS
    volumes:
      - ./Containers/PROXY/Config/default.conf:/etc/nginx/conf.d/default.conf
      - ./Containers/PROXY/Config/nginx.conf:/etc/nginx/nginx.conf
      - ./Containers/PROXY/Config/ssl:/etc/nginx/ssl

volumes:
  # web1
  db_data:
  wp_data:
  # web2
  db_data2:
  wp_data2:

networks:
  beach-network:
    driver: bridge
  proxy-praia:
    external: true
