services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns_container
    ports:
      - "53:53/udp"
    networks:
      - asa-networks
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy_container # Criar ou mudar o nome de um existente
    ports:
      - "80:80/tcp"
    networks:
      - asa-networks
  
  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    container_name: email
    ports:
      - "25:25/tcp"   # SEMP
      - "587:587/tcp" # SMP Client
      - "110:110/tcp" # POP3
      - "143:143/tcp" # IMAP
    networks:
      - asa-networks

networks:
  asa-networks:
    driver: bridge