services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns_container
    ports:
      - "53:53/udp"
    # networks:
    #   - asa-networks
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy_container # Criar ou mudar o nome de um existente
    ports:
      - "80:80/tcp"
    networks:
      - asa-networks
  
  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    container_name: email
    ports:
      - "25:25/tcp"   # SEMP
      - "587:587/tcp" # SMP Client
      - "110:110/tcp" # POP3
      - "143:143/tcp" # IMAP
    networks:
      - asa-networks

  webmail:
    image: roundcube/roundcubemail
    container_name: roundcube
    restart: always
    #ports:
    #  - "8080:80"  # Roundcube acessível via http://localhost:8080
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=imap://email
      - ROUNDCUBEMAIL_SMTP_SERVER=smtp://email
    volumes:
      - ./roundcube/data:/var/www/html
    networks:
      - asa-networks

networks:
  asa-networks:
    driver: bridge